spring.cloud.stream:
  bindings:
    uppercase|echo-in-0:
      destination: uppercase-in
  function:
    definition: uppercase|echo

#  kafka:
#    streams:
#      binder:
#        applicationId: uppercase-processor
#        configuration:
#          commit.interval.ms: 100
#          default:
#            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde